trainer:
  gpus: [6,7]
  precision: 16
  gradient_clip_val: 1.0
  weights_save_path: /raid/scratch/wuws/docker/v12_weighted_mapq/model/v16
  val_check_interval: 0.2
model:
  gru_input_dim: 128
  gru_hidden_dim: 128
  gru_n_layers: 1
  gru_dropout: 0.0
  lr: 3e-4
data:
  data_dir: /mnt/projects/miles-wgs-wenshan/wuws_m/v12/v12_train
  val_path: /mnt/projects/miles-wgs-wenshan/wuws_m/v12/v12_val
  batch_size: 64
  mem: False
  workers: 4