trainer:
  gpus: [4, 5]
  precision: 16
  gradient_clip_val: 1.0
  weights_save_path: /Roko/checkpoints/v18
  val_check_interval: 0.2
model:
  gru_hidden_dim: 128
  gru_n_layers: 2
  gru_dropout: 0.0
  lr: 3e-4
data:
  data_dir: /Roko/features/train
  val_path: /Roko/features/val
  batch_size: 128
  mem: False
  workers: 4
