wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.7
    start_time: 1633341825
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      3:
      - 1
      - 7
      4: 3.9.7
      5: 0.12.3
      8:
      - 5
