wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_embedding\.weight_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_fc1\.weight_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_fc1\.bias_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_fc2\.weight_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_fc2\.bias_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_ih_l0_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_hh_l0_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_ih_l0_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_hh_l0_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_ih_l0_reverse_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_hh_l0_reverse_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_ih_l0_reverse_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_hh_l0_reverse_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_ih_l1_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_hh_l1_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_ih_l1_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_hh_l1_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_ih_l1_reverse_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_hh_l1_reverse_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_ih_l1_reverse_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_hh_l1_reverse_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_ih_l2_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_hh_l2_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_ih_l2_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_hh_l2_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_ih_l2_reverse_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_hh_l2_reverse_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_ih_l2_reverse_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_hh_l2_reverse_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_fc4\.weight_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_fc4\.bias_step
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_total_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: gradients/fc4\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/fc4\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/fc4\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/fc4\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/fc4\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/fc4\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l0._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l0.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l0.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l0._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l0.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l0.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l0_reverse._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l0_reverse.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l0_reverse.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l1_reverse._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l1_reverse.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l1_reverse.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l2_reverse._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l2_reverse.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l2_reverse.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l2_reverse._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l2_reverse.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l2_reverse.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l2_reverse._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l2_reverse.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l2_reverse.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l2_reverse._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l2_reverse.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l2_reverse.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l2._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l2.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l2.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l2._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l2.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l2.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l2._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l2.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l2.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l2._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l2.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l2.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l1_reverse._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l1_reverse.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l1_reverse.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l1_reverse._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l1_reverse.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l1_reverse.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l0_reverse._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l0_reverse.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l0_reverse.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l1._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l1.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l1.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l1._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l1.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l1.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l1._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l1.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_hh_l1.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l1._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l1.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.weight_ih_l1.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l0_reverse._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l0_reverse.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l0_reverse.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l1_reverse._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l1_reverse.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l1_reverse.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l0._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l0.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l0.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l0_reverse._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l0_reverse.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_ih_l0_reverse.bins
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l0._type
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l0.values
      5: 1
      6:
      - 1
    - 1: gradients/gru\.bias_hh_l0.bins
      5: 1
      6:
      - 1
    - 1: gradients/fc2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/fc2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/fc2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/fc2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/fc2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/fc2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/fc1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/fc1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/fc1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/fc1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/fc1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/fc1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/embedding\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/embedding\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/embedding\.weight.bins
      5: 1
      6:
      - 1
    - 1: val_acc_batch
      5: 1
      6:
      - 1
    - 1: val_loss_batch
      5: 1
      6:
      - 1
    - 1: val_acc_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_embedding\.weight_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_fc1\.weight_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_fc1\.bias_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_fc2\.weight_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_fc2\.bias_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_ih_l0_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_hh_l0_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_ih_l0_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_hh_l0_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_ih_l0_reverse_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_hh_l0_reverse_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_ih_l0_reverse_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_hh_l0_reverse_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_ih_l1_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_hh_l1_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_ih_l1_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_hh_l1_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_ih_l1_reverse_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_hh_l1_reverse_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_ih_l1_reverse_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_hh_l1_reverse_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_ih_l2_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_hh_l2_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_ih_l2_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_hh_l2_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_ih_l2_reverse_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.weight_hh_l2_reverse_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_ih_l2_reverse_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_gru\.bias_hh_l2_reverse_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_fc4\.weight_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_fc4\.bias_epoch
      5: 1
      6:
      - 1
    - 1: grad_2\.0_norm_total_epoch
      5: 1
      6:
      - 1
    - 1: Train_acc_epoch
      5: 1
      6:
      - 1
    python_version: 3.9.7
    start_time: 1634530676
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      3:
      - 1
      - 7
      4: 3.9.7
      5: 0.12.1
      8:
      - 5
